In [2]:
from mxnet import nd

In [5]:
nd.zeros((3,4))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [6]:
x = nd.ones((3,4))
x


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [7]:
nd.array([[1,2],[2,3]])


[[1. 2.]
 [2. 3.]]
<NDArray 2x2 @cpu(0)>

创建一个 均值为0, 方差为1服从正太分部的随机数组

In [10]:
y = nd.random_normal(0, 1, shape=(3,4))
y


[[-0.68106437 -0.13531584  0.37723127  0.41016445]
 [ 0.5712682  -2.7579627   1.07628    -0.6141326 ]
 [ 1.8307649  -1.1468065   0.05383795 -2.5074806 ]]
<NDArray 3x4 @cpu(0)>

In [11]:
y.shape

(3, 4)

In [12]:
y.size

12

In [13]:
x + y


[[ 0.31893563  0.86468416  1.3772312   1.4101645 ]
 [ 1.5712682  -1.7579627   2.07628     0.38586742]
 [ 2.8307648  -0.14680648  1.053838   -1.5074806 ]]
<NDArray 3x4 @cpu(0)>

In [14]:
x * y


[[-0.68106437 -0.13531584  0.37723127  0.41016445]
 [ 0.5712682  -2.7579627   1.07628    -0.6141326 ]
 [ 1.8307649  -1.1468065   0.05383795 -2.5074806 ]]
<NDArray 3x4 @cpu(0)>

In [15]:
nd.exp(y)


[[0.50607806 0.87344    1.4582415  1.5070657 ]
 [1.770511   0.06342085 2.9337456  0.54111004]
 [6.2386565  0.31764957 1.0553136  0.08147325]]
<NDArray 3x4 @cpu(0)>

In [16]:
nd.dot(x, y.T)


[[-0.02898449 -1.7245471  -1.7696842 ]
 [-0.02898449 -1.7245471  -1.7696842 ]
 [-0.02898449 -1.7245471  -1.7696843 ]]
<NDArray 3x3 @cpu(0)>