In [1]:
import numpy as np

In [3]:
a = np.array([
    [1402, 191],
    [1371, 821],
    [949, 1437],
    [147, 1448]
])

a

array([[1402,  191],
       [1371,  821],
       [ 949, 1437],
       [ 147, 1448]])

In [4]:
a + a

array([[2804,  382],
       [2742, 1642],
       [1898, 2874],
       [ 294, 2896]])

In [5]:
a 

array([[1402,  191],
       [1371,  821],
       [ 949, 1437],
       [ 147, 1448]])

In [24]:
a = np.array([
    [1,4],
    [2,5],
    [3,6]
])
b = np.array([
    [1,5],
    [2,5]
])

a.T.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
from mxnet import nd

In [29]:
x = nd.arange(12)
x


[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.]
<NDArray 12 @cpu(0)>

In [30]:
x.shape

(12,)

In [31]:
x.size

12

In [32]:
x.reshape(3,4)


[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]
<NDArray 3x4 @cpu(0)>

In [33]:
x.reshape(4,3)


[[  0.   1.   2.]
 [  3.   4.   5.]
 [  6.   7.   8.]
 [  9.  10.  11.]]
<NDArray 4x3 @cpu(0)>

In [34]:
nd.zeros((2,3,4))


[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]
<NDArray 2x3x4 @cpu(0)>

In [35]:
nd.ones((2,3,4))


[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]
<NDArray 2x3x4 @cpu(0)>

In [44]:
x = nd.array([[1,2],[3,4]])

随机生成一个均为0, 标准差为1的服从正太分别的NDArray

In [37]:
nd.random.normal(0, 1, shape= (3,4))


[[ 1.16307867  0.48380461  0.29956347  0.15302546]
 [-1.16881478  1.55807114 -0.54594457 -2.35562968]
 [ 0.54144019  2.67850661  1.25463438 -0.54877394]]
<NDArray 3x4 @cpu(0)>

In [53]:
y = nd.ones((x.shape))

y = y + y

In [54]:
x * y


[[ 2.  4.]
 [ 6.  8.]]
<NDArray 2x2 @cpu(0)>

In [57]:
x / y


[[ 0.5  1. ]
 [ 1.5  2. ]]
<NDArray 2x2 @cpu(0)>

### 指数运算

In [58]:
y.exp()


[[ 7.38905621  7.38905621]
 [ 7.38905621  7.38905621]]
<NDArray 2x2 @cpu(0)>

### 矩阵运算

In [59]:
nd.dot(x, y)


[[  6.   6.]
 [ 14.  14.]]
<NDArray 2x2 @cpu(0)>

In [60]:
x 


[[ 1.  2.]
 [ 3.  4.]]
<NDArray 2x2 @cpu(0)>

In [61]:
y


[[ 2.  2.]
 [ 2.  2.]]
<NDArray 2x2 @cpu(0)>

In [65]:
nd.concat(x,y, dim = 1), nd.concat(x, y ,dim = 0)

(
 [[ 1.  2.  2.  2.]
  [ 3.  4.  2.  2.]]
 <NDArray 2x4 @cpu(0)>, 
 [[ 1.  2.]
  [ 3.  4.]
  [ 2.  2.]
  [ 2.  2.]]
 <NDArray 4x2 @cpu(0)>)

In [66]:
x == y


[[ 0.  1.]
 [ 0.  0.]]
<NDArray 2x2 @cpu(0)>

In [68]:
x.sum(), y.sum()

(
 [ 10.]
 <NDArray 1 @cpu(0)>, 
 [ 8.]
 <NDArray 1 @cpu(0)>)

In [72]:
x.norm().asscalar()

5.4772258

## 广播机制

In [73]:
a = nd.arange(3).reshape((3,1))
b = nd.arange(2).reshape((1,2))
a, b

(
 [[ 0.]
  [ 1.]
  [ 2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[ 0.  1.]]
 <NDArray 1x2 @cpu(0)>)

In [74]:
a + b


[[ 0.  1.]
 [ 1.  2.]
 [ 2.  3.]]
<NDArray 3x2 @cpu(0)>

# 自动求梯度

In [75]:
from mxnet import autograd, nd

In [77]:
x = nd.arange(4).reshape((4,1))
x


[[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]]
<NDArray 4x1 @cpu(0)>

调用attach_gread 函数申请存储梯度的内存

In [78]:
x.attach_grad()

In [79]:
help(nd.normal)

Help on function normal:

normal(loc=_Null, scale=_Null, shape=_Null, ctx=_Null, dtype=_Null, out=None, name=None, **kwargs)
    Draw random samples from a normal (Gaussian) distribution.
    
    .. note:: The existing alias ``normal`` is deprecated.
    
    Samples are distributed according to a normal distribution parametrized by *loc* (mean) and *scale* (standard deviation).
    
    Example::
    
       normal(loc=0, scale=1, shape=(2,2)) = [[ 1.89171135, -1.16881478],
                                              [-1.23474145,  1.55807114]]
    
    
    Defined in src/operator/random/sample_op.cc:L85
    
    Parameters
    ----------
    loc : float, optional, default=0
        Mean of the distribution.
    scale : float, optional, default=1
        Standard deviation of the distribution.
    shape : Shape(tuple), optional, default=[]
        Shape of the output.
    ctx : string, optional, default=''
        Context of output, in format [cpu|gpu|cpu_pinned](n). Only used for